#%RAML 1.0 DataType
displayName: Authorized Distributors with Stock Reports
type: object
properties:
  "date?":
    displayName: Date
    description: date
    type: string
  avgQuantity?:
    displayName: Avg Quantity
    description: avg-quantity
    type: string
  inventory?:
    displayName: Inventory
    description: inventory
    type: string