#%RAML 1.0 DataType
displayName: Authenticate user response object
description: Defines the fields for Authenticate user response datatype

type: object
properties:
  status:
    type: object
    properties:
      code:
        displayName: Code
        description: code
        type: string
      message:
        displayName: Message
        description: message
        type: string
      success:
        displayName: Success
        description: success
        type: string
      jSessionId:
        displayName: Success
        description: success
        type: string