#%RAML 1.0 DataType
displayName: Chemical Dto
type: object
properties:
  totalMassInGram?:
    displayName: Total Mass In Gram
    description: total-mass-in-gram
    type: string
  totalMassSummationInGram?:
    displayName: Feature Value
    description: feature-value
    type: string
  locationName?:
    displayName: Location Name
    description: location-name
    type: string
  homogenousMaterial?:
    displayName: Homogenous Material
    description: homogenous-material
    type: string
  homogenousMaterialMass?:
    displayName: Homogenous Material Mass
    description: homogenous-material-mass
    type: string
  substanceIdentification?:
    displayName: Substance Identification
    description: substance-identification
    type: string
  normalizedSubstance?:
    displayName: Normalized Substance
    description: normalized-substance
    type: string
  substanceGroup?:
    displayName: Substance Group
    description: substance-group
    type: string
  substanceMass?:
    displayName: Substance Mass
    description: substance-mass
    type: string
  ppm?:
    displayName: PPM
    description: ppm
    type: string
  casNumber?:
    displayName: CAS Number
    description: cas-number
    type: string
  mdsurl?:
    displayName: MDSURL
    description: mdsurl
    type: string
  itemSubItem?:
    displayName: Item Sub Item
    description: item-sub-item
    type: string