#%RAML 1.0 DataType
displayName: Country Of Origin
type: object
properties:
  country?:
    displayName: Country
    description: country
    type: string
  source?:
    displayName: Source
    description: source
    type: string