#%RAML 1.0 DataType
displayName: Cross Dto
type: object
properties:
  crossComId?:
    displayName: Cross Com Id
    description: cross-com-id
    type: string
  crossPartNumber?:
    displayName: Cross Part Number
    description: cross-part-number
    type: string
  crossManufacturer?:
    displayName: Cross Manufacturer
    description: cross-manufacturer
    type: string
  crossType?:
    displayName: Cross Type
    description: cross-type
    type: string
  comment?:
    displayName: Comment
    description: comment
    type: string