#%RAML 1.0 DataType
displayName: Datasheet
type: object
properties:
  date?:
    displayName: date
    description: date
    type: string
  url?:
    displayName: url
    description: url
    type: string