#%RAML 1.0 DataType
displayName: Franchised Inventory Dto
type: object
properties:
  distributor?:
    displayName: Distributor
    description: distributor
    type: string
  quantity?:
    displayName: Quantity
    description: quantity
    type: string
  buyNowLink?:
    displayName: Buy Now Link
    description: buy-now-link
    type: string