#%RAML 1.0 DataType
displayName: Lifecycle
type: object
properties:
  "date?":
    displayName: Date
    description: "date"
    type: string
  lifecycle?:
    displayName: Lifecycle
    description: lifecycle
    type: string
  partNumber?:
    displayName: Part Number
    description: part-number
    type: string
  manufacturerName?:
    displayName: Manufacturer Name
    description: manufacturer-name
    type: string
  reasonOfChange?:
    displayName: Reason Of Change
    description: reason-of-change
    type: string
  sourceName?:
    displayName: Source Name
    description: source-name
    type: string
  sourceUrl?:
    displayName: Source URL
    description: source-url
    type: string