#%RAML 1.0 DataType
displayName: Man Counterfeit Reports
type: object
properties:
  mpn?:
    displayName: MPN
    description: mpn
    type: string
  supplier?:
    displayName: Supplier
    description: supplier
    type: string
  notificationDate?:
    displayName: Notification Date
    description: notification-date
    type: string
  counterfitMethods?:
    displayName: Counterfit Methods
    description: counterfit-methods
    type: string
  "description?":
    displayName: Description
    description: "description"
    type: string
  source?:
    displayName: Source
    description: source
    type: string	