#%RAML 1.0 DataType
displayName: PCN Dto
type: object
properties:
  pcnNumber?:
    displayName: PCN Number
    description: pcn-number
    type: string
  typeOfChange?:
    displayName: Type Of Change
    description: type-of-change
    type: string
  descriptionOfChange?:
    displayName: Description Of Change
    description: description-of-change
    type: string
  pcnSource?:
    displayName: Pcn Source
    description: pcn-source
    type: string
  notificationDate?:
    displayName: Notification Date
    description: notification-date
    type: string
  effectiveDate?:
    displayName: Effective Date
    description: effective-date
    type: string
  lastTimeBuyDate?:
    displayName: Last Time Buy Date
    description: last-time-buy-date
    type: string
  lastShipDate?:
    displayName: Last Ship Date
    description: last-ship-date
    type: string
  pcnId?:
    displayName: PCN Id
    description: pcn-id
    type: string