#%RAML 1.0 DataType
displayName: Price Breaks Dto
type: object
properties:
  priceBreak?:
    displayName: Price Break
    description: price-break
    type: string
  averagePrice?:
    displayName: Average Price
    description: average-price
    type: string
  minPrice?:
    displayName: Min Price
    description: min-price
    type: string